### ISSUE TITLE
date selection error

### ISSUE THREAD

**Issue by alperozisik** [smartface/sf-component-calendar#14]
**Step 1**
Init calendar with the following code in constructor:
```javascript
const myCalendar = page.myCalendar = new Calendar({
  useRangeSelection: true,
  //theme: customTheme,
  justCurrentDays: true,
  useDaySelection: true
});
myCalendar.onDaySelect = function(dateInfo) {
  alert(JSON.stringify(dateInfo, null, "\t"), "onDaySelect");
};
```
**Step 2**
Press on any date. Following error is given
![cal select err](https://user-images.githubusercontent.com/7248325/38193384-7ca1bbb8-367a-11e8-83b5-1a1c61d47a28.png)

**Comment by cenkce** [comment]
Fixed at 2.0.0-rc.10
