### ISSUE TITLE
Managing the API by Timestamp

### ISSUE THREAD

**Issue by furkanarabaci** [smartface/sf-component-calendar#20]
We should be able to create or manage the calendar API by passing it EPOCH based time.

**Comment by illegalDisease** [comment]
In vanilla JavaScript, we can get the current EPOCH time with
`new Date().getTime()` returns `1535706594613`, which points out the current time in miliseconds.

Just a ramdom use case, we should be able to set the date using this number like this : 

`this.calendar.setSelectedTimestamp(new Date().getTime())`

or passing it to setSelectedDate function. That way, #16 will have one more solution as well.

**Comment by cenkce** [comment]
You can already use Date object.
