### ISSUE TITLE
changeCalendar, specialDays to be a function

### ISSUE THREAD

**Issue by alperozisik** [smartface/sf-component-calendar#6]
changeCalendar should accept specialDays should be a function, accepting day as argument, returning true or false OR special day style for that day.

Sample usages that come to my mind:
```js
changeCalendar("en", "gregorian", function(day) {
  return day.getDay() % 2 === 0;
});
```
Also
```js
var dayColors = ["#ff0000",  "#00ff00", "#0000ff"];
changeCalendar("en", "gregorian", function(day) {
  var selectedColor = dayColors[day.getDay()];
  if(!selectedColor)
    return null; //or false or undefined
 else
    return { backgroundColor: selectedColor });
});
```

**Comment by cenkce** [comment]
You can't do that because of it breaks styling logic. If you create some use-cases that we should cover, I can create another solution.
