### ISSUE TITLE
Paths are broken on 2.0.0-rc.2

### ISSUE THREAD

**Issue by alperozisik** [smartface/sf-component-calendar#8]
As you regularly install it on a Smartface workspace the package does not work.

I have fixed the paths and attached. I did not go through fixing in place

[sf-component-calendar.tar.gz](https://github.com/smartface/sf-component-calendar/files/1862077/sf-component-calendar.tar.gz)

**Comment by cenkce** [comment]
Fixed at 2.0.0-rc.8

**Comment by alperozisik** [comment]
:thumbsup:
