### ISSUE TITLE
Calendar Theme does not update from theme json files

### ISSUE THREAD

**Issue by alperozisik** [smartface/sf-component-calendar#9]
I have created a calendar style.json file. It is not affecting the calendar. It should?
[common.json.txt](https://github.com/smartface/sf-component-calendar/files/1862083/common.json.txt)

**Comment by cenkce** [comment]
This feature is on the road-map.

**Comment by alperozisik** [comment]
Let's keep this as an issue, but not as a bug & and not related to this v2.0 release
